// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: examples/crud/protobuf/service.proto

package crud

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_ROLE_UNSPECIFIED Role = 0
	Role_ADMIN            Role = 1
	Role_EDITOR           Role = 2
	Role_VIEWER           Role = 3
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ADMIN",
		2: "EDITOR",
		3: "VIEWER",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ADMIN":            1,
		"EDITOR":           2,
		"VIEWER":           3,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_examples_crud_protobuf_service_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_examples_crud_protobuf_service_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_examples_crud_protobuf_service_proto_rawDescGZIP(), []int{0}
}

type IEnum int32

const (
	IEnum_IENUM_UNSPECIFIED IEnum = 0
	IEnum_VALUE_1           IEnum = 1
	IEnum_VALUE_2           IEnum = 2
	IEnum_VALUE_4           IEnum = 4
	IEnum_VALUE_8           IEnum = 8
	IEnum_VALUE_16          IEnum = 16
)

// Enum value maps for IEnum.
var (
	IEnum_name = map[int32]string{
		0:  "IENUM_UNSPECIFIED",
		1:  "VALUE_1",
		2:  "VALUE_2",
		4:  "VALUE_4",
		8:  "VALUE_8",
		16: "VALUE_16",
	}
	IEnum_value = map[string]int32{
		"IENUM_UNSPECIFIED": 0,
		"VALUE_1":           1,
		"VALUE_2":           2,
		"VALUE_4":           4,
		"VALUE_8":           8,
		"VALUE_16":          16,
	}
)

func (x IEnum) Enum() *IEnum {
	p := new(IEnum)
	*p = x
	return p
}

func (x IEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_examples_crud_protobuf_service_proto_enumTypes[1].Descriptor()
}

func (IEnum) Type() protoreflect.EnumType {
	return &file_examples_crud_protobuf_service_proto_enumTypes[1]
}

func (x IEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IEnum.Descriptor instead.
func (IEnum) EnumDescriptor() ([]byte, []int) {
	return file_examples_crud_protobuf_service_proto_rawDescGZIP(), []int{1}
}

// Subtypes
type Name struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	First         string                 `protobuf:"bytes,1,opt,name=first,proto3" json:"first,omitempty"`
	Middle        string                 `protobuf:"bytes,2,opt,name=middle,proto3" json:"middle,omitempty"`
	Last          string                 `protobuf:"bytes,3,opt,name=last,proto3" json:"last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Name) Reset() {
	*x = Name{}
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Name) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Name) ProtoMessage() {}

func (x *Name) ProtoReflect() protoreflect.Message {
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Name.ProtoReflect.Descriptor instead.
func (*Name) Descriptor() ([]byte, []int) {
	return file_examples_crud_protobuf_service_proto_rawDescGZIP(), []int{0}
}

func (x *Name) GetFirst() string {
	if x != nil {
		return x.First
	}
	return ""
}

func (x *Name) GetMiddle() string {
	if x != nil {
		return x.Middle
	}
	return ""
}

func (x *Name) GetLast() string {
	if x != nil {
		return x.Last
	}
	return ""
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	PostalCode    string                 `protobuf:"bytes,3,opt,name=postalCode,proto3" json:"postalCode,omitempty"`
	Country       string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_examples_crud_protobuf_service_proto_rawDescGZIP(), []int{1}
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type Contact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Address       *Address               `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contact) Reset() {
	*x = Contact{}
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_examples_crud_protobuf_service_proto_rawDescGZIP(), []int{2}
}

func (x *Contact) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Contact) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Contact) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

// Main Person entity
type Person struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUID
	Name          *Name                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Contact       *Contact               `protobuf:"bytes,4,opt,name=contact,proto3" json:"contact,omitempty"`
	Roles         []Role                 `protobuf:"varint,5,rep,packed,name=roles,proto3,enum=person.Role" json:"roles,omitempty"`
	IsActive      bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Ienum         IEnum                  `protobuf:"varint,8,opt,name=ienum,proto3,enum=person.IEnum" json:"ienum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Person) Reset() {
	*x = Person{}
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_examples_crud_protobuf_service_proto_rawDescGZIP(), []int{3}
}

func (x *Person) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Person) GetName() *Name {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Person) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Person) GetContact() *Contact {
	if x != nil {
		return x.Contact
	}
	return nil
}

func (x *Person) GetRoles() []Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *Person) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Person) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Person) GetIenum() IEnum {
	if x != nil {
		return x.Ienum
	}
	return IEnum_IENUM_UNSPECIFIED
}

// CRUD request/response messages
type CreatePersonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Person        *Person                `protobuf:"bytes,1,opt,name=person,proto3" json:"person,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePersonRequest) Reset() {
	*x = CreatePersonRequest{}
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePersonRequest) ProtoMessage() {}

func (x *CreatePersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePersonRequest.ProtoReflect.Descriptor instead.
func (*CreatePersonRequest) Descriptor() ([]byte, []int) {
	return file_examples_crud_protobuf_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePersonRequest) GetPerson() *Person {
	if x != nil {
		return x.Person
	}
	return nil
}

type CreatePersonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Person        *Person                `protobuf:"bytes,1,opt,name=person,proto3" json:"person,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePersonResponse) Reset() {
	*x = CreatePersonResponse{}
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePersonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePersonResponse) ProtoMessage() {}

func (x *CreatePersonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePersonResponse.ProtoReflect.Descriptor instead.
func (*CreatePersonResponse) Descriptor() ([]byte, []int) {
	return file_examples_crud_protobuf_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreatePersonResponse) GetPerson() *Person {
	if x != nil {
		return x.Person
	}
	return nil
}

type GetPersonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPersonRequest) Reset() {
	*x = GetPersonRequest{}
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPersonRequest) ProtoMessage() {}

func (x *GetPersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPersonRequest.ProtoReflect.Descriptor instead.
func (*GetPersonRequest) Descriptor() ([]byte, []int) {
	return file_examples_crud_protobuf_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetPersonRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPersonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Person        *Person                `protobuf:"bytes,1,opt,name=person,proto3" json:"person,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPersonResponse) Reset() {
	*x = GetPersonResponse{}
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPersonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPersonResponse) ProtoMessage() {}

func (x *GetPersonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPersonResponse.ProtoReflect.Descriptor instead.
func (*GetPersonResponse) Descriptor() ([]byte, []int) {
	return file_examples_crud_protobuf_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetPersonResponse) GetPerson() *Person {
	if x != nil {
		return x.Person
	}
	return nil
}

type UpdatePersonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Person        *Person                `protobuf:"bytes,1,opt,name=person,proto3" json:"person,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePersonRequest) Reset() {
	*x = UpdatePersonRequest{}
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePersonRequest) ProtoMessage() {}

func (x *UpdatePersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePersonRequest.ProtoReflect.Descriptor instead.
func (*UpdatePersonRequest) Descriptor() ([]byte, []int) {
	return file_examples_crud_protobuf_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdatePersonRequest) GetPerson() *Person {
	if x != nil {
		return x.Person
	}
	return nil
}

type UpdatePersonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Person        *Person                `protobuf:"bytes,1,opt,name=person,proto3" json:"person,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePersonResponse) Reset() {
	*x = UpdatePersonResponse{}
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePersonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePersonResponse) ProtoMessage() {}

func (x *UpdatePersonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePersonResponse.ProtoReflect.Descriptor instead.
func (*UpdatePersonResponse) Descriptor() ([]byte, []int) {
	return file_examples_crud_protobuf_service_proto_rawDescGZIP(), []int{9}
}

func (x *UpdatePersonResponse) GetPerson() *Person {
	if x != nil {
		return x.Person
	}
	return nil
}

type DeletePersonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePersonRequest) Reset() {
	*x = DeletePersonRequest{}
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePersonRequest) ProtoMessage() {}

func (x *DeletePersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePersonRequest.ProtoReflect.Descriptor instead.
func (*DeletePersonRequest) Descriptor() ([]byte, []int) {
	return file_examples_crud_protobuf_service_proto_rawDescGZIP(), []int{10}
}

func (x *DeletePersonRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePersonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePersonResponse) Reset() {
	*x = DeletePersonResponse{}
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePersonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePersonResponse) ProtoMessage() {}

func (x *DeletePersonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePersonResponse.ProtoReflect.Descriptor instead.
func (*DeletePersonResponse) Descriptor() ([]byte, []int) {
	return file_examples_crud_protobuf_service_proto_rawDescGZIP(), []int{11}
}

func (x *DeletePersonResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListPersonsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPersonsRequest) Reset() {
	*x = ListPersonsRequest{}
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPersonsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPersonsRequest) ProtoMessage() {}

func (x *ListPersonsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPersonsRequest.ProtoReflect.Descriptor instead.
func (*ListPersonsRequest) Descriptor() ([]byte, []int) {
	return file_examples_crud_protobuf_service_proto_rawDescGZIP(), []int{12}
}

func (x *ListPersonsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPersonsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListPersonsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Persons       []*Person              `protobuf:"bytes,1,rep,name=persons,proto3" json:"persons,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPersonsResponse) Reset() {
	*x = ListPersonsResponse{}
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPersonsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPersonsResponse) ProtoMessage() {}

func (x *ListPersonsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPersonsResponse.ProtoReflect.Descriptor instead.
func (*ListPersonsResponse) Descriptor() ([]byte, []int) {
	return file_examples_crud_protobuf_service_proto_rawDescGZIP(), []int{13}
}

func (x *ListPersonsResponse) GetPersons() []*Person {
	if x != nil {
		return x.Persons
	}
	return nil
}

func (x *ListPersonsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_examples_crud_protobuf_service_proto protoreflect.FileDescriptor

const file_examples_crud_protobuf_service_proto_rawDesc = "" +
	"\n" +
	"$examples/crud/protobuf/service.proto\x12\x06person\x1a\x1fgoogle/protobuf/timestamp.proto\"H\n" +
	"\x04Name\x12\x14\n" +
	"\x05first\x18\x01 \x01(\tR\x05first\x12\x16\n" +
	"\x06middle\x18\x02 \x01(\tR\x06middle\x12\x12\n" +
	"\x04last\x18\x03 \x01(\tR\x04last\"o\n" +
	"\aAddress\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x1e\n" +
	"\n" +
	"postalCode\x18\x03 \x01(\tR\n" +
	"postalCode\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\"`\n" +
	"\aContact\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12)\n" +
	"\aaddress\x18\x03 \x01(\v2\x0f.person.AddressR\aaddress\"\x98\x02\n" +
	"\x06Person\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\x04name\x18\x02 \x01(\v2\f.person.NameR\x04name\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x05R\x03age\x12)\n" +
	"\acontact\x18\x04 \x01(\v2\x0f.person.ContactR\acontact\x12\"\n" +
	"\x05roles\x18\x05 \x03(\x0e2\f.person.RoleR\x05roles\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12#\n" +
	"\x05ienum\x18\b \x01(\x0e2\r.person.IEnumR\x05ienum\"=\n" +
	"\x13CreatePersonRequest\x12&\n" +
	"\x06person\x18\x01 \x01(\v2\x0e.person.PersonR\x06person\">\n" +
	"\x14CreatePersonResponse\x12&\n" +
	"\x06person\x18\x01 \x01(\v2\x0e.person.PersonR\x06person\"\"\n" +
	"\x10GetPersonRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\";\n" +
	"\x11GetPersonResponse\x12&\n" +
	"\x06person\x18\x01 \x01(\v2\x0e.person.PersonR\x06person\"=\n" +
	"\x13UpdatePersonRequest\x12&\n" +
	"\x06person\x18\x01 \x01(\v2\x0e.person.PersonR\x06person\">\n" +
	"\x14UpdatePersonResponse\x12&\n" +
	"\x06person\x18\x01 \x01(\v2\x0e.person.PersonR\x06person\"%\n" +
	"\x13DeletePersonRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\x14DeletePersonResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"P\n" +
	"\x12ListPersonsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"g\n" +
	"\x13ListPersonsResponse\x12(\n" +
	"\apersons\x18\x01 \x03(\v2\x0e.person.PersonR\apersons\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken*?\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05ADMIN\x10\x01\x12\n" +
	"\n" +
	"\x06EDITOR\x10\x02\x12\n" +
	"\n" +
	"\x06VIEWER\x10\x03*`\n" +
	"\x05IEnum\x12\x15\n" +
	"\x11IENUM_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aVALUE_1\x10\x01\x12\v\n" +
	"\aVALUE_2\x10\x02\x12\v\n" +
	"\aVALUE_4\x10\x04\x12\v\n" +
	"\aVALUE_8\x10\b\x12\f\n" +
	"\bVALUE_16\x10\x102\xfa\x02\n" +
	"\rPersonService\x12I\n" +
	"\fCreatePerson\x12\x1b.person.CreatePersonRequest\x1a\x1c.person.CreatePersonResponse\x12@\n" +
	"\tGetPerson\x12\x18.person.GetPersonRequest\x1a\x19.person.GetPersonResponse\x12I\n" +
	"\fUpdatePerson\x12\x1b.person.UpdatePersonRequest\x1a\x1c.person.UpdatePersonResponse\x12I\n" +
	"\fDeletePerson\x12\x1b.person.DeletePersonRequest\x1a\x1c.person.DeletePersonResponse\x12F\n" +
	"\vListPersons\x12\x1a.person.ListPersonsRequest\x1a\x1b.person.ListPersonsResponseB'Z%github.com/okieoth/hort/examples/crudb\x06proto3"

var (
	file_examples_crud_protobuf_service_proto_rawDescOnce sync.Once
	file_examples_crud_protobuf_service_proto_rawDescData []byte
)

func file_examples_crud_protobuf_service_proto_rawDescGZIP() []byte {
	file_examples_crud_protobuf_service_proto_rawDescOnce.Do(func() {
		file_examples_crud_protobuf_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_crud_protobuf_service_proto_rawDesc), len(file_examples_crud_protobuf_service_proto_rawDesc)))
	})
	return file_examples_crud_protobuf_service_proto_rawDescData
}

var file_examples_crud_protobuf_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_examples_crud_protobuf_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_examples_crud_protobuf_service_proto_goTypes = []any{
	(Role)(0),                     // 0: person.Role
	(IEnum)(0),                    // 1: person.IEnum
	(*Name)(nil),                  // 2: person.Name
	(*Address)(nil),               // 3: person.Address
	(*Contact)(nil),               // 4: person.Contact
	(*Person)(nil),                // 5: person.Person
	(*CreatePersonRequest)(nil),   // 6: person.CreatePersonRequest
	(*CreatePersonResponse)(nil),  // 7: person.CreatePersonResponse
	(*GetPersonRequest)(nil),      // 8: person.GetPersonRequest
	(*GetPersonResponse)(nil),     // 9: person.GetPersonResponse
	(*UpdatePersonRequest)(nil),   // 10: person.UpdatePersonRequest
	(*UpdatePersonResponse)(nil),  // 11: person.UpdatePersonResponse
	(*DeletePersonRequest)(nil),   // 12: person.DeletePersonRequest
	(*DeletePersonResponse)(nil),  // 13: person.DeletePersonResponse
	(*ListPersonsRequest)(nil),    // 14: person.ListPersonsRequest
	(*ListPersonsResponse)(nil),   // 15: person.ListPersonsResponse
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
}
var file_examples_crud_protobuf_service_proto_depIdxs = []int32{
	3,  // 0: person.Contact.address:type_name -> person.Address
	2,  // 1: person.Person.name:type_name -> person.Name
	4,  // 2: person.Person.contact:type_name -> person.Contact
	0,  // 3: person.Person.roles:type_name -> person.Role
	16, // 4: person.Person.created_at:type_name -> google.protobuf.Timestamp
	1,  // 5: person.Person.ienum:type_name -> person.IEnum
	5,  // 6: person.CreatePersonRequest.person:type_name -> person.Person
	5,  // 7: person.CreatePersonResponse.person:type_name -> person.Person
	5,  // 8: person.GetPersonResponse.person:type_name -> person.Person
	5,  // 9: person.UpdatePersonRequest.person:type_name -> person.Person
	5,  // 10: person.UpdatePersonResponse.person:type_name -> person.Person
	5,  // 11: person.ListPersonsResponse.persons:type_name -> person.Person
	6,  // 12: person.PersonService.CreatePerson:input_type -> person.CreatePersonRequest
	8,  // 13: person.PersonService.GetPerson:input_type -> person.GetPersonRequest
	10, // 14: person.PersonService.UpdatePerson:input_type -> person.UpdatePersonRequest
	12, // 15: person.PersonService.DeletePerson:input_type -> person.DeletePersonRequest
	14, // 16: person.PersonService.ListPersons:input_type -> person.ListPersonsRequest
	7,  // 17: person.PersonService.CreatePerson:output_type -> person.CreatePersonResponse
	9,  // 18: person.PersonService.GetPerson:output_type -> person.GetPersonResponse
	11, // 19: person.PersonService.UpdatePerson:output_type -> person.UpdatePersonResponse
	13, // 20: person.PersonService.DeletePerson:output_type -> person.DeletePersonResponse
	15, // 21: person.PersonService.ListPersons:output_type -> person.ListPersonsResponse
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_examples_crud_protobuf_service_proto_init() }
func file_examples_crud_protobuf_service_proto_init() {
	if File_examples_crud_protobuf_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_crud_protobuf_service_proto_rawDesc), len(file_examples_crud_protobuf_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_crud_protobuf_service_proto_goTypes,
		DependencyIndexes: file_examples_crud_protobuf_service_proto_depIdxs,
		EnumInfos:         file_examples_crud_protobuf_service_proto_enumTypes,
		MessageInfos:      file_examples_crud_protobuf_service_proto_msgTypes,
	}.Build()
	File_examples_crud_protobuf_service_proto = out.File
	file_examples_crud_protobuf_service_proto_goTypes = nil
	file_examples_crud_protobuf_service_proto_depIdxs = nil
}
