// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: examples/crud/protobuf/service.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PersonIEnum int32

const (
	PersonIEnum_PERSONIENUM_UNSPECIFIED PersonIEnum = 0
	PersonIEnum_VALUE_1                 PersonIEnum = 1
	PersonIEnum_VALUE_2                 PersonIEnum = 2
	PersonIEnum_VALUE_4                 PersonIEnum = 4
	PersonIEnum_VALUE_8                 PersonIEnum = 8
	PersonIEnum_VALUE_16                PersonIEnum = 16
)

// Enum value maps for PersonIEnum.
var (
	PersonIEnum_name = map[int32]string{
		0:  "PERSONIENUM_UNSPECIFIED",
		1:  "VALUE_1",
		2:  "VALUE_2",
		4:  "VALUE_4",
		8:  "VALUE_8",
		16: "VALUE_16",
	}
	PersonIEnum_value = map[string]int32{
		"PERSONIENUM_UNSPECIFIED": 0,
		"VALUE_1":                 1,
		"VALUE_2":                 2,
		"VALUE_4":                 4,
		"VALUE_8":                 8,
		"VALUE_16":                16,
	}
)

func (x PersonIEnum) Enum() *PersonIEnum {
	p := new(PersonIEnum)
	*p = x
	return p
}

func (x PersonIEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PersonIEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_examples_crud_protobuf_service_proto_enumTypes[0].Descriptor()
}

func (PersonIEnum) Type() protoreflect.EnumType {
	return &file_examples_crud_protobuf_service_proto_enumTypes[0]
}

func (x PersonIEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PersonIEnum.Descriptor instead.
func (PersonIEnum) EnumDescriptor() ([]byte, []int) {
	return file_examples_crud_protobuf_service_proto_rawDescGZIP(), []int{0}
}

type PersonRolesItems int32

const (
	PersonRolesItems_PERSONROLESITEMS_UNSPECIFIED PersonRolesItems = 0
	PersonRolesItems_ADMIN                        PersonRolesItems = 1
	PersonRolesItems_EDITOR                       PersonRolesItems = 2
	PersonRolesItems_VIEWER                       PersonRolesItems = 3
)

// Enum value maps for PersonRolesItems.
var (
	PersonRolesItems_name = map[int32]string{
		0: "PERSONROLESITEMS_UNSPECIFIED",
		1: "ADMIN",
		2: "EDITOR",
		3: "VIEWER",
	}
	PersonRolesItems_value = map[string]int32{
		"PERSONROLESITEMS_UNSPECIFIED": 0,
		"ADMIN":                        1,
		"EDITOR":                       2,
		"VIEWER":                       3,
	}
)

func (x PersonRolesItems) Enum() *PersonRolesItems {
	p := new(PersonRolesItems)
	*p = x
	return p
}

func (x PersonRolesItems) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PersonRolesItems) Descriptor() protoreflect.EnumDescriptor {
	return file_examples_crud_protobuf_service_proto_enumTypes[1].Descriptor()
}

func (PersonRolesItems) Type() protoreflect.EnumType {
	return &file_examples_crud_protobuf_service_proto_enumTypes[1]
}

func (x PersonRolesItems) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PersonRolesItems.Descriptor instead.
func (PersonRolesItems) EnumDescriptor() ([]byte, []int) {
	return file_examples_crud_protobuf_service_proto_rawDescGZIP(), []int{1}
}

type Person struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Age           int32                  `protobuf:"varint,1,opt,name=age,proto3" json:"age,omitempty"`
	Contact       *PersonContact         `protobuf:"bytes,2,opt,name=contact,proto3" json:"contact,omitempty"`
	Roles         []PersonRolesItems     `protobuf:"varint,3,rep,packed,name=roles,proto3,enum=person.PersonRolesItems" json:"roles,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=isActive,proto3" json:"isActive,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	IEnum         PersonIEnum            `protobuf:"varint,6,opt,name=iEnum,proto3,enum=person.PersonIEnum" json:"iEnum,omitempty"`
	Id            string                 `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	Name          *PersonName            `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Person) Reset() {
	*x = Person{}
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_examples_crud_protobuf_service_proto_rawDescGZIP(), []int{0}
}

func (x *Person) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Person) GetContact() *PersonContact {
	if x != nil {
		return x.Contact
	}
	return nil
}

func (x *Person) GetRoles() []PersonRolesItems {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *Person) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Person) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Person) GetIEnum() PersonIEnum {
	if x != nil {
		return x.IEnum
	}
	return PersonIEnum_PERSONIENUM_UNSPECIFIED
}

func (x *Person) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Person) GetName() *PersonName {
	if x != nil {
		return x.Name
	}
	return nil
}

type PersonContact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Address       *PersonContactAddress  `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonContact) Reset() {
	*x = PersonContact{}
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonContact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonContact) ProtoMessage() {}

func (x *PersonContact) ProtoReflect() protoreflect.Message {
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonContact.ProtoReflect.Descriptor instead.
func (*PersonContact) Descriptor() ([]byte, []int) {
	return file_examples_crud_protobuf_service_proto_rawDescGZIP(), []int{1}
}

func (x *PersonContact) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *PersonContact) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *PersonContact) GetAddress() *PersonContactAddress {
	if x != nil {
		return x.Address
	}
	return nil
}

type PersonContactAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	PostalCode    string                 `protobuf:"bytes,3,opt,name=postalCode,proto3" json:"postalCode,omitempty"`
	Country       string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonContactAddress) Reset() {
	*x = PersonContactAddress{}
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonContactAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonContactAddress) ProtoMessage() {}

func (x *PersonContactAddress) ProtoReflect() protoreflect.Message {
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonContactAddress.ProtoReflect.Descriptor instead.
func (*PersonContactAddress) Descriptor() ([]byte, []int) {
	return file_examples_crud_protobuf_service_proto_rawDescGZIP(), []int{2}
}

func (x *PersonContactAddress) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *PersonContactAddress) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *PersonContactAddress) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *PersonContactAddress) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type PersonName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	First         string                 `protobuf:"bytes,1,opt,name=first,proto3" json:"first,omitempty"`
	Middle        string                 `protobuf:"bytes,2,opt,name=middle,proto3" json:"middle,omitempty"`
	Last          string                 `protobuf:"bytes,3,opt,name=last,proto3" json:"last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonName) Reset() {
	*x = PersonName{}
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonName) ProtoMessage() {}

func (x *PersonName) ProtoReflect() protoreflect.Message {
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonName.ProtoReflect.Descriptor instead.
func (*PersonName) Descriptor() ([]byte, []int) {
	return file_examples_crud_protobuf_service_proto_rawDescGZIP(), []int{3}
}

func (x *PersonName) GetFirst() string {
	if x != nil {
		return x.First
	}
	return ""
}

func (x *PersonName) GetMiddle() string {
	if x != nil {
		return x.Middle
	}
	return ""
}

func (x *PersonName) GetLast() string {
	if x != nil {
		return x.Last
	}
	return ""
}

type CreatePersonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Person        *Person                `protobuf:"bytes,1,opt,name=person,proto3" json:"person,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePersonRequest) Reset() {
	*x = CreatePersonRequest{}
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePersonRequest) ProtoMessage() {}

func (x *CreatePersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePersonRequest.ProtoReflect.Descriptor instead.
func (*CreatePersonRequest) Descriptor() ([]byte, []int) {
	return file_examples_crud_protobuf_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePersonRequest) GetPerson() *Person {
	if x != nil {
		return x.Person
	}
	return nil
}

type CreatePersonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Person        *Person                `protobuf:"bytes,1,opt,name=person,proto3" json:"person,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePersonResponse) Reset() {
	*x = CreatePersonResponse{}
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePersonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePersonResponse) ProtoMessage() {}

func (x *CreatePersonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePersonResponse.ProtoReflect.Descriptor instead.
func (*CreatePersonResponse) Descriptor() ([]byte, []int) {
	return file_examples_crud_protobuf_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreatePersonResponse) GetPerson() *Person {
	if x != nil {
		return x.Person
	}
	return nil
}

type GetPersonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPersonRequest) Reset() {
	*x = GetPersonRequest{}
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPersonRequest) ProtoMessage() {}

func (x *GetPersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPersonRequest.ProtoReflect.Descriptor instead.
func (*GetPersonRequest) Descriptor() ([]byte, []int) {
	return file_examples_crud_protobuf_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetPersonRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPersonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Person        *Person                `protobuf:"bytes,1,opt,name=person,proto3" json:"person,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPersonResponse) Reset() {
	*x = GetPersonResponse{}
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPersonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPersonResponse) ProtoMessage() {}

func (x *GetPersonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPersonResponse.ProtoReflect.Descriptor instead.
func (*GetPersonResponse) Descriptor() ([]byte, []int) {
	return file_examples_crud_protobuf_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetPersonResponse) GetPerson() *Person {
	if x != nil {
		return x.Person
	}
	return nil
}

type UpdatePersonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Person        *Person                `protobuf:"bytes,1,opt,name=person,proto3" json:"person,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePersonRequest) Reset() {
	*x = UpdatePersonRequest{}
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePersonRequest) ProtoMessage() {}

func (x *UpdatePersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePersonRequest.ProtoReflect.Descriptor instead.
func (*UpdatePersonRequest) Descriptor() ([]byte, []int) {
	return file_examples_crud_protobuf_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdatePersonRequest) GetPerson() *Person {
	if x != nil {
		return x.Person
	}
	return nil
}

type UpdatePersonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Person        *Person                `protobuf:"bytes,1,opt,name=person,proto3" json:"person,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePersonResponse) Reset() {
	*x = UpdatePersonResponse{}
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePersonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePersonResponse) ProtoMessage() {}

func (x *UpdatePersonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePersonResponse.ProtoReflect.Descriptor instead.
func (*UpdatePersonResponse) Descriptor() ([]byte, []int) {
	return file_examples_crud_protobuf_service_proto_rawDescGZIP(), []int{9}
}

func (x *UpdatePersonResponse) GetPerson() *Person {
	if x != nil {
		return x.Person
	}
	return nil
}

type DeletePersonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePersonRequest) Reset() {
	*x = DeletePersonRequest{}
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePersonRequest) ProtoMessage() {}

func (x *DeletePersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePersonRequest.ProtoReflect.Descriptor instead.
func (*DeletePersonRequest) Descriptor() ([]byte, []int) {
	return file_examples_crud_protobuf_service_proto_rawDescGZIP(), []int{10}
}

func (x *DeletePersonRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePersonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePersonResponse) Reset() {
	*x = DeletePersonResponse{}
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePersonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePersonResponse) ProtoMessage() {}

func (x *DeletePersonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePersonResponse.ProtoReflect.Descriptor instead.
func (*DeletePersonResponse) Descriptor() ([]byte, []int) {
	return file_examples_crud_protobuf_service_proto_rawDescGZIP(), []int{11}
}

func (x *DeletePersonResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListPersonsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPersonsRequest) Reset() {
	*x = ListPersonsRequest{}
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPersonsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPersonsRequest) ProtoMessage() {}

func (x *ListPersonsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPersonsRequest.ProtoReflect.Descriptor instead.
func (*ListPersonsRequest) Descriptor() ([]byte, []int) {
	return file_examples_crud_protobuf_service_proto_rawDescGZIP(), []int{12}
}

func (x *ListPersonsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPersonsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListPersonsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Persons       []*Person              `protobuf:"bytes,1,rep,name=persons,proto3" json:"persons,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPersonsResponse) Reset() {
	*x = ListPersonsResponse{}
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPersonsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPersonsResponse) ProtoMessage() {}

func (x *ListPersonsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_crud_protobuf_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPersonsResponse.ProtoReflect.Descriptor instead.
func (*ListPersonsResponse) Descriptor() ([]byte, []int) {
	return file_examples_crud_protobuf_service_proto_rawDescGZIP(), []int{13}
}

func (x *ListPersonsResponse) GetPersons() []*Person {
	if x != nil {
		return x.Persons
	}
	return nil
}

func (x *ListPersonsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_examples_crud_protobuf_service_proto protoreflect.FileDescriptor

const file_examples_crud_protobuf_service_proto_rawDesc = "" +
	"\n" +
	"$examples/crud/protobuf/service.proto\x12\x06person\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb4\x02\n" +
	"\x06Person\x12\x10\n" +
	"\x03age\x18\x01 \x01(\x05R\x03age\x12/\n" +
	"\acontact\x18\x02 \x01(\v2\x15.person.PersonContactR\acontact\x12.\n" +
	"\x05roles\x18\x03 \x03(\x0e2\x18.person.PersonRolesItemsR\x05roles\x12\x1a\n" +
	"\bisActive\x18\x04 \x01(\bR\bisActive\x128\n" +
	"\tcreatedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12)\n" +
	"\x05iEnum\x18\x06 \x01(\x0e2\x13.person.PersonIEnumR\x05iEnum\x12\x0e\n" +
	"\x02id\x18\a \x01(\tR\x02id\x12&\n" +
	"\x04name\x18\b \x01(\v2\x12.person.PersonNameR\x04name\"s\n" +
	"\rPersonContact\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x126\n" +
	"\aaddress\x18\x03 \x01(\v2\x1c.person.PersonContactAddressR\aaddress\"|\n" +
	"\x14PersonContactAddress\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x1e\n" +
	"\n" +
	"postalCode\x18\x03 \x01(\tR\n" +
	"postalCode\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\"N\n" +
	"\n" +
	"PersonName\x12\x14\n" +
	"\x05first\x18\x01 \x01(\tR\x05first\x12\x16\n" +
	"\x06middle\x18\x02 \x01(\tR\x06middle\x12\x12\n" +
	"\x04last\x18\x03 \x01(\tR\x04last\"=\n" +
	"\x13CreatePersonRequest\x12&\n" +
	"\x06person\x18\x01 \x01(\v2\x0e.person.PersonR\x06person\">\n" +
	"\x14CreatePersonResponse\x12&\n" +
	"\x06person\x18\x01 \x01(\v2\x0e.person.PersonR\x06person\"\"\n" +
	"\x10GetPersonRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\";\n" +
	"\x11GetPersonResponse\x12&\n" +
	"\x06person\x18\x01 \x01(\v2\x0e.person.PersonR\x06person\"=\n" +
	"\x13UpdatePersonRequest\x12&\n" +
	"\x06person\x18\x01 \x01(\v2\x0e.person.PersonR\x06person\">\n" +
	"\x14UpdatePersonResponse\x12&\n" +
	"\x06person\x18\x01 \x01(\v2\x0e.person.PersonR\x06person\"%\n" +
	"\x13DeletePersonRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\x14DeletePersonResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"P\n" +
	"\x12ListPersonsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"g\n" +
	"\x13ListPersonsResponse\x12(\n" +
	"\apersons\x18\x01 \x03(\v2\x0e.person.PersonR\apersons\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken*l\n" +
	"\vPersonIEnum\x12\x1b\n" +
	"\x17PERSONIENUM_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aVALUE_1\x10\x01\x12\v\n" +
	"\aVALUE_2\x10\x02\x12\v\n" +
	"\aVALUE_4\x10\x04\x12\v\n" +
	"\aVALUE_8\x10\b\x12\f\n" +
	"\bVALUE_16\x10\x10*W\n" +
	"\x10PersonRolesItems\x12 \n" +
	"\x1cPERSONROLESITEMS_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05ADMIN\x10\x01\x12\n" +
	"\n" +
	"\x06EDITOR\x10\x02\x12\n" +
	"\n" +
	"\x06VIEWER\x10\x032\xfa\x02\n" +
	"\rPersonService\x12I\n" +
	"\fCreatePerson\x12\x1b.person.CreatePersonRequest\x1a\x1c.person.CreatePersonResponse\x12@\n" +
	"\tGetPerson\x12\x18.person.GetPersonRequest\x1a\x19.person.GetPersonResponse\x12I\n" +
	"\fUpdatePerson\x12\x1b.person.UpdatePersonRequest\x1a\x1c.person.UpdatePersonResponse\x12I\n" +
	"\fDeletePerson\x12\x1b.person.DeletePersonRequest\x1a\x1c.person.DeletePersonResponse\x12F\n" +
	"\vListPersons\x12\x1a.person.ListPersonsRequest\x1a\x1b.person.ListPersonsResponseB0Z.github.com/okieoth/hort/examples/crud/protobufb\x06proto3"

var (
	file_examples_crud_protobuf_service_proto_rawDescOnce sync.Once
	file_examples_crud_protobuf_service_proto_rawDescData []byte
)

func file_examples_crud_protobuf_service_proto_rawDescGZIP() []byte {
	file_examples_crud_protobuf_service_proto_rawDescOnce.Do(func() {
		file_examples_crud_protobuf_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_crud_protobuf_service_proto_rawDesc), len(file_examples_crud_protobuf_service_proto_rawDesc)))
	})
	return file_examples_crud_protobuf_service_proto_rawDescData
}

var file_examples_crud_protobuf_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_examples_crud_protobuf_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_examples_crud_protobuf_service_proto_goTypes = []any{
	(PersonIEnum)(0),              // 0: person.PersonIEnum
	(PersonRolesItems)(0),         // 1: person.PersonRolesItems
	(*Person)(nil),                // 2: person.Person
	(*PersonContact)(nil),         // 3: person.PersonContact
	(*PersonContactAddress)(nil),  // 4: person.PersonContactAddress
	(*PersonName)(nil),            // 5: person.PersonName
	(*CreatePersonRequest)(nil),   // 6: person.CreatePersonRequest
	(*CreatePersonResponse)(nil),  // 7: person.CreatePersonResponse
	(*GetPersonRequest)(nil),      // 8: person.GetPersonRequest
	(*GetPersonResponse)(nil),     // 9: person.GetPersonResponse
	(*UpdatePersonRequest)(nil),   // 10: person.UpdatePersonRequest
	(*UpdatePersonResponse)(nil),  // 11: person.UpdatePersonResponse
	(*DeletePersonRequest)(nil),   // 12: person.DeletePersonRequest
	(*DeletePersonResponse)(nil),  // 13: person.DeletePersonResponse
	(*ListPersonsRequest)(nil),    // 14: person.ListPersonsRequest
	(*ListPersonsResponse)(nil),   // 15: person.ListPersonsResponse
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
}
var file_examples_crud_protobuf_service_proto_depIdxs = []int32{
	3,  // 0: person.Person.contact:type_name -> person.PersonContact
	1,  // 1: person.Person.roles:type_name -> person.PersonRolesItems
	16, // 2: person.Person.createdAt:type_name -> google.protobuf.Timestamp
	0,  // 3: person.Person.iEnum:type_name -> person.PersonIEnum
	5,  // 4: person.Person.name:type_name -> person.PersonName
	4,  // 5: person.PersonContact.address:type_name -> person.PersonContactAddress
	2,  // 6: person.CreatePersonRequest.person:type_name -> person.Person
	2,  // 7: person.CreatePersonResponse.person:type_name -> person.Person
	2,  // 8: person.GetPersonResponse.person:type_name -> person.Person
	2,  // 9: person.UpdatePersonRequest.person:type_name -> person.Person
	2,  // 10: person.UpdatePersonResponse.person:type_name -> person.Person
	2,  // 11: person.ListPersonsResponse.persons:type_name -> person.Person
	6,  // 12: person.PersonService.CreatePerson:input_type -> person.CreatePersonRequest
	8,  // 13: person.PersonService.GetPerson:input_type -> person.GetPersonRequest
	10, // 14: person.PersonService.UpdatePerson:input_type -> person.UpdatePersonRequest
	12, // 15: person.PersonService.DeletePerson:input_type -> person.DeletePersonRequest
	14, // 16: person.PersonService.ListPersons:input_type -> person.ListPersonsRequest
	7,  // 17: person.PersonService.CreatePerson:output_type -> person.CreatePersonResponse
	9,  // 18: person.PersonService.GetPerson:output_type -> person.GetPersonResponse
	11, // 19: person.PersonService.UpdatePerson:output_type -> person.UpdatePersonResponse
	13, // 20: person.PersonService.DeletePerson:output_type -> person.DeletePersonResponse
	15, // 21: person.PersonService.ListPersons:output_type -> person.ListPersonsResponse
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_examples_crud_protobuf_service_proto_init() }
func file_examples_crud_protobuf_service_proto_init() {
	if File_examples_crud_protobuf_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_crud_protobuf_service_proto_rawDesc), len(file_examples_crud_protobuf_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_crud_protobuf_service_proto_goTypes,
		DependencyIndexes: file_examples_crud_protobuf_service_proto_depIdxs,
		EnumInfos:         file_examples_crud_protobuf_service_proto_enumTypes,
		MessageInfos:      file_examples_crud_protobuf_service_proto_msgTypes,
	}.Build()
	File_examples_crud_protobuf_service_proto = out.File
	file_examples_crud_protobuf_service_proto_goTypes = nil
	file_examples_crud_protobuf_service_proto_depIdxs = nil
}
