name: go

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.24.x
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.x"
      - name: Test with the Go CLI
        run: make test
