name: go

on:
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install sqlite3
              run: sudo apt-get update && sudo apt-get install -y sqlite3 protobuf-compiler
            - name: Setup Go 1.25.x
              uses: actions/setup-go@v4
              with:
                  go-version: "1.25.x"
            - name: Install go proto codegen
              run: |
                  go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
                  go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
            - name: Test with the Go CLI
              run: make test
